parameters:
    storm.media.twig.extension.class:          Storm\MediaBundle\Twig\MediaExtension
    storm.media.templating.helper.class:       Storm\MediaBundle\Templating\MediaHelper

services:
    # Managers
#    storm.media.gallery_manager:
#        class: Storm\MediaBundle\Media\GalleryManager

    storm.media.media_factory:
        class: Storm\MediaBundle\Media\MediaFactory
        arguments:
            - %storm.media.types%

    # Doctrine
    storm.media.doctrine.metadata.listener:
        class: Storm\MediaBundle\Listener\LoadMetadataListener
        arguments:
            - @storm.media.media_factory
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    # Templating
    storm.media.templating.helper:
        class: %storm.media.templating.helper.class%
        arguments:
            - @templating
            - @storm.media.media_factory
        tags:
            - { name: templating.helper }

    storm.media.twig.extension:
        class: %storm.media.twig.extension.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }